version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - SOLANA_RPC_URL=${SOLANA_RPC_URL:-https://api.mainnet-beta.solana.com}
      - BASE_RPC_URL=${BASE_RPC_URL:-https://mainnet.base.org}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - chonk9k-network

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=chonk9k
      - POSTGRES_USER=chonk9k_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - chonk9k-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - chonk9k-network

volumes:
  postgres_data:

networks:
  chonk9k-network:
    driver: bridge